import type { ReportType } from '@prisma/client';
import type { TaskClass } from '@/lib/ai/provider';
import { taskClassForReport } from '@/lib/ai/router';

/**
 * Report templates. Each defines the retrieval query used to gather grounding
 * excerpts and the instruction appended to the system prompt. Output is
 * Markdown with inline citations; DOCX/PDF exporters can render from it later.
 */

export interface ReportTemplate {
  type: ReportType;
  label: string;
  description: string;
  taskClass: TaskClass;
  /** Seed query used to retrieve relevant chunks for grounding. */
  retrievalQuery: string;
  /** Instruction appended to the grounded system prompt. */
  instruction: string;
}

export const REPORT_TEMPLATES: Record<ReportType, ReportTemplate> = {
  DOCUMENT_SUMMARY: {
    type: 'DOCUMENT_SUMMARY',
    label: 'Document Summary',
    description: 'A concise summary of the selected documents.',
    taskClass: taskClassForReport('DOCUMENT_SUMMARY'),
    retrievalQuery: 'overall summary purpose scope key points of this document',
    instruction:
      'Produce a structured Markdown summary with sections: Overview, Key Points, and Notable Details. Cite sources with [n].',
  },
  REQUIREMENTS_EXTRACTION: {
    type: 'REQUIREMENTS_EXTRACTION',
    label: 'Requirements Extraction',
    description: 'Extract explicit requirements, obligations, and deliverables.',
    taskClass: taskClassForReport('REQUIREMENTS_EXTRACTION'),
    retrievalQuery: 'requirements shall must obligations deliverables scope of work',
    instruction:
      'Extract every explicit requirement or obligation as a Markdown table with columns: ID, Requirement, Source. Only include requirements supported by the excerpts. Cite with [n].',
  },
  RISK_ANALYSIS: {
    type: 'RISK_ANALYSIS',
    label: 'Risk Analysis',
    description: 'Identify risks, ambiguities, and unfavorable terms.',
    taskClass: taskClassForReport('RISK_ANALYSIS'),
    retrievalQuery: 'risk liability penalty termination indemnification deadline ambiguity',
    instruction:
      'Identify risks and unfavorable terms. For each: Risk, Severity (Low/Medium/High), Rationale, Source [n]. Note where evidence is insufficient rather than speculating.',
  },
  COMPLIANCE_MATRIX: {
    type: 'COMPLIANCE_MATRIX',
    label: 'Compliance Matrix',
    description: 'Map requirements to a compliance response structure.',
    taskClass: taskClassForReport('COMPLIANCE_MATRIX'),
    retrievalQuery: 'requirement clause compliance section reference standard FAR DFARS',
    instruction:
      'Build a compliance matrix as a Markdown table: Requirement, Reference/Clause, Compliance Approach (leave blank if not stated), Source [n].',
  },
  COMPARISON: {
    type: 'COMPARISON',
    label: 'Comparison Report',
    description: 'Compare terms, requirements, or figures across documents.',
    taskClass: taskClassForReport('COMPARISON'),
    retrievalQuery: 'differences comparison terms pricing scope between documents',
    instruction:
      'Compare the selected documents. Present a Markdown table of key dimensions and how each document addresses them. Cite each cell with [n].',
  },
  EXECUTIVE_BRIEF: {
    type: 'EXECUTIVE_BRIEF',
    label: 'Executive Brief',
    description: 'A leadership-ready one-page brief.',
    taskClass: taskClassForReport('EXECUTIVE_BRIEF'),
    retrievalQuery: 'executive summary decision recommendation opportunity key figures',
    instruction:
      'Write a one-page executive brief: Situation, Key Findings, Recommendation, Next Steps. Keep it tight. Cite with [n].',
  },
  ACTION_ITEMS: {
    type: 'ACTION_ITEMS',
    label: 'Action-Item List',
    description: 'Extract concrete action items and owners.',
    taskClass: taskClassForReport('ACTION_ITEMS'),
    retrievalQuery: 'action item task follow up owner due date next steps',
    instruction:
      'Extract concrete action items as a Markdown checklist. Where an owner or due date is stated, include it. Cite with [n]. Do not invent owners or dates.',
  },
};

export const EVIDENCE_DISCLAIMER =
  '> **Evidence disclaimer:** This report is generated by an AI model from retrieved excerpts of your uploaded documents. It may be incomplete or contain errors. Verify all findings against the source documents before relying on them.';
